#Enable actuator management endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /manage

#Info endpoint parameters.
info:
    app:
      name: Sprint boot based Auth application
      description: This is a sample application for demonstrating basic authentication functionality
      version: 1.0.0
    java-vendor : ${java.specification.vendor}

#Spring data & JPA config.
spring:
  datasource:
    url: jdbc:mysql://mysql-docker:3306/auth?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springuser
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: false
  

#Error mapping
application:
        error:
          mapping: a:b